# Generated by Django 3.2.8 on 2021-10-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211023_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_on_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
